version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_TTL=${REDIS_TTL}

  redis:
    image: redis:6.2
    container_name: redis-cache
    ports:
      - "6379:6379"

  tests:
    build: .
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
    command: vendor/bin/phpunit --colors=always --testdox
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_TTL=${REDIS_TTL}

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    depends_on:
      - redis
